# Generated by Django 5.2.8 on 2026-03-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_remove_customuser_shipping_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="pending_delete",
        ),
    ]
