# Generated by Django 5.2.8 on 2026-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "product",
            "0003_alter_category_created_at_alter_category_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="reserved_stock",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
