# Generated by Django 5.2.8 on 2026-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_product_reserved_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="reserved_stock",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                help_text="Unit terkunci di checkout yang belum dibayar. Dikelola otomatis, jangan edit manual jika tidak diperlukan. Stok bisa dijual = stock - reserved_stock.",
            ),
        ),
    ]
