# Generated by Django 5.2.8 on 2026-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_alter_store_created_at_alter_store_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="enable_insurance",
            field=models.BooleanField(
                default=True,
                help_text="Aktifkan atau nonaktifkan asuransi pengiriman otomatis.",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="insurance_paid_by_customer",
            field=models.BooleanField(
                default=True,
                help_text="Tentukan apakah biaya asuransi dibebankan kepada pembeli.",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="insurance_threshold",
            field=models.PositiveIntegerField(
                default=300000,
                help_text="Minimal total produk agar asuransi diterapkan.",
            ),
        ),
    ]
