# Generated by Django 5.2.8 on 2025-12-23 14:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="courier",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "order_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("canceled", "Canceled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("canceled_at", models.DateTimeField(blank=True, null=True)),
                ("is_archived", models.BooleanField(default=False)),
                ("shipping_cost", models.PositiveIntegerField(default=0)),
                ("shipping_cashback", models.PositiveIntegerField(default=0)),
                ("courier_code", models.CharField(max_length=10)),
                ("shipping_type", models.CharField(max_length=20)),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("BANK TRANSFER", "Bank Transfer"),
                            ("COD", "Cash On Delivery"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="unpaid",
                        max_length=20,
                    ),
                ),
                ("service_fee", models.PositiveIntegerField(default=0)),
                ("additional_cost", models.PositiveIntegerField(default=0)),
                ("cod_value", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "insurance_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("origin_ro", models.IntegerField()),
                ("origin_address", models.TextField()),
                ("destination_ro", models.IntegerField()),
                ("destination_address", models.TextField()),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to="store.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("product_name", models.CharField(max_length=255)),
                ("product_variant_name", models.CharField(max_length=255)),
                ("product_weight", models.PositiveIntegerField()),
                ("product_price", models.DecimalField(decimal_places=2, max_digits=18)),
                ("qty", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
