# Generated by Django 5.2.8 on 2025-12-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_courier_created_at_courier_updated_at_order_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="insurance_value",
        ),
    ]
