# Generated by Django 5.2.8 on 2026-03-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0005_alter_checkoutsession_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_archived",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
