# Generated by Django 5.2.8 on 2026-06-06 16:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0006_remove_order_is_archived_orderitem_is_archived"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderShipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "shipping_name",
                    models.CharField(
                        help_text="Nama kurir yang dipilih saat checkout.",
                        max_length=30,
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        help_text="Layanan pengiriman yang dipilih saat checkout.",
                        max_length=50,
                    ),
                ),
                (
                    "shipping_weight",
                    models.DecimalField(
                        decimal_places=3,
                        default=0,
                        editable=False,
                        help_text="Snapshot berat total pesanan saat checkout.",
                        max_digits=10,
                    ),
                ),
                (
                    "etd",
                    models.CharField(
                        help_text="Estimasi waktu pengiriman.", max_length=50
                    ),
                ),
                ("shipping_cost", models.PositiveIntegerField(default=0)),
                ("shipping_cashback", models.PositiveIntegerField(default=0)),
                (
                    "shipping_cost_net",
                    models.PositiveIntegerField(
                        help_text="Snapshot ongkir setelah dikurangi cashback."
                    ),
                ),
                (
                    "insurance_value",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="Snapshot biaya asuransi saat order dibuat. Tidak berubah meskipun konfigurasi toko atau kurir berubah.",
                    ),
                ),
                ("service_fee", models.PositiveIntegerField()),
                ("additional_cost", models.PositiveIntegerField(default=0)),
                ("origin_ro", models.IntegerField()),
                ("origin_address", models.TextField()),
                ("destination_ro", models.IntegerField()),
                ("destination_address", models.TextField()),
                ("order_id_ro", models.CharField(blank=True, max_length=20, null=True)),
                ("order_no_ro", models.CharField(blank=True, max_length=50, null=True)),
                ("cod_value", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShippingInsurance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shipping", models.CharField(max_length=50, unique=True)),
                ("rate", models.DecimalField(decimal_places=4, max_digits=5)),
                ("admin_fee", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Courier",
        ),
        migrations.RemoveField(
            model_name="order",
            name="additional_cost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="cod_value",
        ),
        migrations.RemoveField(
            model_name="order",
            name="courier_code",
        ),
        migrations.RemoveField(
            model_name="order",
            name="destination_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="destination_ro",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_id_ro",
        ),
        migrations.RemoveField(
            model_name="order",
            name="order_no_ro",
        ),
        migrations.RemoveField(
            model_name="order",
            name="origin_address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="origin_ro",
        ),
        migrations.RemoveField(
            model_name="order",
            name="service_fee",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_cashback",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_cost",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_type",
        ),
        migrations.AddField(
            model_name="checkoutsession",
            name="order",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="actual_net_income",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Snapshot pendapatan bersih akhir yang diterima toko saat order dibuat.",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="grand_total",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Snapshot total pembayaran saat order dibuat. Tidak berubah meskipun konfigurasi toko atau kurir berubah.",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="net_income",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Snapshot pendapatan bersih hasil perhitungan ongkir saat order dibuat.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BANK TRANSFER", "Bank Transfer"),
                    ("COD", "Cash On Delivery"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ordershipping",
            name="order",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipping",
                to="order.order",
            ),
        ),
    ]
