# Generated by Django 5.2.8 on 2026-06-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_ordershipping_shippinginsurance_delete_courier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
