# Generated by Django 5.2.8 on 2026-06-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0008_alter_order_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="ordershipping",
            name="shipping_weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                editable=False,
                help_text="Snapshot berat total (Kg) pesanan saat checkout.",
                max_digits=10,
            ),
        ),
    ]
