# Generated by Django 5.2.8 on 2026-06-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0009_alter_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordershipping",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                help_text="Nomor resi pengiriman dari kurir, diisi manual oleh admin setelah packing.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
