# Generated by Django 5.2.8 on 2026-06-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0010_ordershipping_tracking_number_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reduced_stock",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
