# Generated by Django 5.2.8 on 2026-07-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0011_order_reduced_stock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordershipping",
            name="order_id_ro",
        ),
        migrations.RemoveField(
            model_name="ordershipping",
            name="order_no_ro",
        ),
    ]
