# Generated by Django 5.2.8 on 2026-07-16 16:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0012_remove_ordershipping_order_id_ro_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="canceled_at",
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("unpaid", "Unpaid"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="reduced_stock",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="True setelah reduce_stock() webhook sukses sekali. Tidak berubah saat refund/cancel per item — cek RefundRequest untuk status stock item.",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.PositiveIntegerField(
                        editable=False,
                        help_text="Diambil otomatis dari subtotal order_item, tidak bisa diisi customer.",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("customer_cancel", "Dibatalkan Customer"),
                            ("out_of_stock", "Stok Habis"),
                            ("return", "Retur Pasca-Kirim"),
                            ("other", "Lainnya"),
                        ],
                        help_text="Otomatis diisi CUSTOMER_CANCEL/RETURN saat customer mengajukan. Admin bisa ubah manual (mis. jadi OUT_OF_STOCK) sebelum status COMPLETED.",
                        max_length=30,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Catatan tambahan dari customer saat mengajukan refund.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                (
                    "destination_type",
                    models.CharField(
                        choices=[("bank", "Transfer Bank"), ("ewallet", "E-Wallet")],
                        max_length=10,
                    ),
                ),
                (
                    "destination_provider",
                    models.CharField(
                        choices=[
                            ("bca", "BCA"),
                            ("mandiri", "Mandiri"),
                            ("bni", "BNI"),
                            ("bri", "BRI"),
                            ("permata", "Permata"),
                            ("cimb", "CIMB Niaga"),
                            ("gopay", "GoPay"),
                            ("shopeepay", "ShopeePay"),
                            ("dana", "DANA"),
                            ("ovo", "OVO"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "destination_number",
                    models.CharField(
                        help_text="Nomor rekening atau nomor HP e-wallet tujuan refund.",
                        max_length=50,
                    ),
                ),
                (
                    "account_holder_name",
                    models.CharField(
                        help_text="Nama pemilik rekening/e-wallet, untuk verifikasi admin sebelum transfer manual.",
                        max_length=150,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refund_requests",
                        to="order.orderitem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
