# Generated by Django 5.2.8 on 2026-06-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipping_address",
            "0004_alter_city_created_at_alter_city_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="destination_id",
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
