# Generated by Django 5.2.8 on 2026-06-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_address", "0005_shippingaddress_destination_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="destination_id",
            field=models.IntegerField(),
        ),
    ]
