# Generated by Django 5.2.8 on 2026-06-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_address", "0006_alter_shippingaddress_destination_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="shippingaddress",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=7, max_digits=10, null=True
            ),
        ),
    ]
