# Generated by Django 5.2.8 on 2026-06-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping_address", "0007_shippingaddress_latitude_shippingaddress_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingaddress",
            name="latitude",
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shippingaddress",
            name="longitude",
            field=models.DecimalField(decimal_places=7, default="0", max_digits=10),
            preserve_default=False,
        ),
    ]
